import io
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.backends.backend_pdf import PdfPages
from datetime import datetime
def _style_fig(fig):
    fig.patch.set_facecolor("#07080f")
def _style_ax(ax):
    ax.set_facecolor("#0e0f1a")
    ax.tick_params(colors="#5a5f7a", labelsize=8)
    for spine in ax.spines.values():
        spine.set_color("#1e2035")
def generate_pdf_report(df: pd.DataFrame, eda: dict, ml_result: dict | None, filename: str) -> bytes:
    """
    Generates a multi-page PDF report and returns it as bytes.
    """
    buf = io.BytesIO()
    with PdfPages(buf) as pdf:
        fig = plt.figure(figsize=(11, 8.5))
        _style_fig(fig)
        ax = fig.add_axes([0, 0, 1, 1])
        ax.set_facecolor("#07080f")
        ax.axis("off")
        ax.text(0.08, 0.88, "autoeda", fontsize=44, fontweight="bold", color="#4f8eff",
                fontfamily="monospace", transform=ax.transAxes)
        ax.text(0.08 + 0.195, 0.885, "PRO", fontsize=20, fontweight="bold", color="#5a5f7a",
                fontfamily="monospace", transform=ax.transAxes)
        ax.text(0.08, 0.80, "Automated Exploratory Data Analysis Report",
                fontsize=14, color="#dde1f0", transform=ax.transAxes)
        ax.axhline(y=0.77, xmin=0.08, xmax=0.92, color="#1e2035", linewidth=1.5)
        info_lines = [
            f"File:        {filename}",
            f"Generated:   {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            f"Rows:        {len(df):,}",
            f"Columns:     {len(df.columns)}",
            f"Numeric:     {eda['n_numeric']}",
            f"Categorical: {eda['n_categorical']}",
            f"Quality:     {eda['quality_score']}/100",
            f"Issues:      {len(eda['issues'])}",
        ]
        for i, line in enumerate(info_lines):
            ax.text(0.08, 0.72 - i * 0.055, line, fontsize=11, color="#dde1f0",
                    fontfamily="monospace", transform=ax.transAxes)

        ax.text(0.08, 0.28, "DATA QUALITY ISSUES", fontsize=9, color="#5a5f7a",
                fontfamily="monospace",  transform=ax.transAxes)
        ax.axhline(y=0.265, xmin=0.08, xmax=0.92, color="#1e2035", linewidth=0.8)
        sev_colors = {"high": "#ff5572", "med": "#f5c542", "info": "#4f8eff"}
        for i, issue in enumerate(eda["issues"][:8]):
            color = sev_colors.get(issue["sev"], "#dde1f0")
            ax.text(0.08, 0.24 - i * 0.032, f"[{issue['sev'].upper()}] {issue['msg']}",
                    fontsize=8, color=color, fontfamily="monospace", transform=ax.transAxes)
        if not eda["issues"]:
            ax.text(0.08, 0.24, "✓ No issues detected", fontsize=9, color="#22d3a0",
                    fontfamily="monospace", transform=ax.transAxes)
        ax.text(0.08, 0.04, "Generated by AutoEDA Pro · github.com/ashmit-chatterjee/autoeda-pro",
                fontsize=8, color="#383d56", fontfamily="monospace", transform=ax.transAxes)
        pdf.savefig(fig, bbox_inches="tight", facecolor="#07080f")
        plt.close(fig)
        num_cols = [c for c in df.columns if eda["column_info"][c]["type"] == "numeric"]
        if num_cols:
            n_cols_grid = min(3, len(num_cols))
            rows_needed = (len(num_cols) + n_cols_grid - 1) // n_cols_grid
            fig, axes = plt.subplots(rows_needed, n_cols_grid,
                                     figsize=(11, max(4, rows_needed * 3)))
            _style_fig(fig)
            fig.suptitle("Numeric Column Distributions", color="#dde1f0",
                         fontsize=14, fontfamily="monospace", y=1.01)
            if rows_needed == 1 and n_cols_grid == 1:
                axes = np.array([[axes]])
            elif rows_needed == 1:
                axes = axes.reshape(1, -1)
            elif n_cols_grid == 1:
                axes = axes.reshape(-1, 1)
            for idx, col in enumerate(num_cols):
                row, c = divmod(idx, n_cols_grid)
                ax = axes[row][c]
                _style_ax(ax)
                series = df[col].dropna()
                ax.hist(series, bins=25, color="#4f8eff", alpha=0.8, edgecolor="#07080f")
                ax.axvline(series.mean(), color="#22d3a0", linewidth=1.5, linestyle="--",
                           label=f"μ={series.mean():.2f}")
                ax.axvline(series.median(), color="#f5c542", linewidth=1.5, linestyle=":",
                           label=f"m={series.median():.2f}")
                ax.set_title(col, color="#dde1f0", fontsize=9, fontfamily="monospace", pad=6)
                ax.legend(fontsize=7, labelcolor="#dde1f0", facecolor="#13141f",
                          edgecolor="#1e2035", framealpha=0.9)
            for idx in range(len(num_cols), rows_needed * n_cols_grid):
                row, c = divmod(idx, n_cols_grid)
                axes[row][c].set_visible(False)
            plt.tight_layout()
            pdf.savefig(fig, bbox_inches="tight", facecolor="#07080f")
            plt.close(fig)
        num_df = df.select_dtypes(include=[np.number]).dropna(axis=1, how="all")
        if num_df.shape[1] >= 2:
            import seaborn as sns
            corr = num_df.corr()
            fig, ax = plt.subplots(figsize=(11, max(5, num_df.shape[1] * 0.8)))
            _style_fig(fig)
            _style_ax(ax)
            fig.suptitle("Correlation Heatmap", color="#dde1f0",
                         fontsize=14, fontfamily="monospace")
            cmap = sns.diverging_palette(220, 10, as_cmap=True)
            mask = np.triu(np.ones_like(corr, dtype=bool))
            sns.heatmap(corr, mask=mask, cmap=cmap, center=0, annot=True, fmt=".2f",
                        ax=ax, linewidths=0.5, linecolor="#1e2035",
                        cbar_kws={"shrink": 0.8},
                        annot_kws={"size": 8, "color": "white"})
            ax.tick_params(colors="#dde1f0", labelsize=9)
            plt.xticks(rotation=45, ha="right", color="#dde1f0")
            plt.yticks(color="#dde1f0")
            plt.tight_layout()
            pdf.savefig(fig, bbox_inches="tight", facecolor="#07080f")
            plt.close(fig)
        if ml_result:
            fig = plt.figure(figsize=(11, 8.5))
            _style_fig(fig)
            gs = gridspec.GridSpec(2, 2, figure=fig)
            ax1 = fig.add_subplot(gs[0, 0])
            _style_ax(ax1)
            names = [m["name"] for m in ml_result["models"]]
            metric_key = "r2" if ml_result["task"] == "regression" else "accuracy"
            scores = [m.get(metric_key, 0) for m in ml_result["models"]]
            colors_bar = ["#22d3a0" if n == ml_result["best_model"] else "#2d3a5e" for n in names]
            ax1.barh(names, scores, color=colors_bar, height=0.6)
            ax1.set_title(f"Model Comparison ({metric_key.upper()})", color="#dde1f0",
                          fontsize=10, fontfamily="monospace")
            ax1.invert_yaxis()
            ax1.set_xlim(0, 1)
            ax2 = fig.add_subplot(gs[0, 1])
            _style_ax(ax2)
            imp = ml_result["feature_importance"][:8]
            imp_names = [x["col"] for x in imp]
            imp_vals = [x["importance"] for x in imp]
            ax2.barh(imp_names, imp_vals, color="#4f8eff", height=0.6)
            ax2.invert_yaxis()
            ax2.set_title("Feature Importance", color="#dde1f0",
                          fontsize=10, fontfamily="monospace")
            if "predictions" in ml_result and ml_result["predictions"]:
                ax3 = fig.add_subplot(gs[1, 0])
                _style_ax(ax3)
                preds = np.array(ml_result["predictions"])
                actuals = np.array(ml_result["actuals"])
                residuals = actuals - preds
                ax3.scatter(preds, residuals, color="#4f8eff", alpha=0.5, s=15)
                ax3.axhline(0, color="#22d3a0", linewidth=1.5, linestyle="--")
                ax3.set_xlabel("Predicted", color="#5a5f7a", fontsize=8)
                ax3.set_ylabel("Residuals", color="#5a5f7a", fontsize=8)
                ax3.set_title("Residuals vs Predicted", color="#dde1f0",
                              fontsize=10, fontfamily="monospace")
                ax4 = fig.add_subplot(gs[1, 1])
                _style_ax(ax4)
                ax4.hist(residuals, bins=25, color="#b87fff", alpha=0.8, edgecolor="#07080f")
                ax4.set_title("Residual Distribution", color="#dde1f0",
                              fontsize=10, fontfamily="monospace")
            elif "confusion_matrix" in ml_result:
                import seaborn as sns
                ax3 = fig.add_subplot(gs[1, :])
                _style_ax(ax3)
                sns.heatmap(np.array(ml_result["confusion_matrix"]), annot=True, fmt="d",
                            cmap="Blues", ax=ax3, linewidths=0.5, linecolor="#1e2035",
                            annot_kws={"color": "white", "size": 11})
                ax3.set_title("Confusion Matrix", color="#dde1f0",
                              fontsize=10, fontfamily="monospace")
            fig.suptitle(f"AutoML Results — Target: {ml_result['target']}",
                         color="#dde1f0", fontsize=13, fontfamily="monospace")
            plt.tight_layout()
            pdf.savefig(fig, bbox_inches="tight", facecolor="#07080f")
            plt.close(fig)
        fig, ax = plt.subplots(figsize=(11, 8.5))
        _style_fig(fig)
        ax.set_facecolor("#07080f")
        ax.axis("off")
        ax.set_title("Column Statistics Summary", color="#dde1f0",
                     fontsize=13, fontfamily="monospace", pad=20)
        rows_data = []
        col_headers = ["Column", "Type", "Missing%", "Unique", "Mean/Top", "Std/Count", "Skew", "Outliers"]
        for col in df.columns:
            info = eda["column_info"][col]
            if info["type"] == "numeric":
                rows_data.append([
                    col[:18], "num",
                    f"{info['missing_pct']}%",
                    str(info["unique"]),
                    str(info.get("mean", "—")),
                    str(info.get("std", "—")),
                    str(info.get("skew", "—")),
                    str(info.get("outliers", "—")),
                ])
            else:
                top = list(info.get("top_values", {}).items())
                top_val = top[0][0][:12] if top else "—"
                top_cnt = top[0][1] if top else "—"
                rows_data.append([
                    col[:18], "cat",
                    f"{info['missing_pct']}%",
                    str(info["unique"]),
                    str(top_val),
                    str(top_cnt),
                    "—", "—",
                ])

        table = ax.table(
            cellText=rows_data,
            colLabels=col_headers,
            loc="center",
            cellLoc="left",
        )
        table.auto_set_font_size(False)
        table.set_fontsize(8)
        table.scale(1, 1.6)

        for (row, col), cell in table.get_celld().items():
            cell.set_facecolor("#13141f" if row > 0 else "#0e0f1a")
            cell.set_text_props(color="#dde1f0" if row > 0 else "#5a5f7a",
                                fontfamily="monospace")
            cell.set_edgecolor("#1e2035")

        plt.tight_layout()
        pdf.savefig(fig, bbox_inches="tight", facecolor="#07080f")
        plt.close(fig)
    buf.seek(0)
    return buf.read()
